language: node_js
node_js:
  - '14'
dist: trusty
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install --save-dev
script:
  - npm run lint
  - npm run test
  - npm run build
